### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by sp2ong** [SkyAndy/svxrdb#1]
I would like to say THANK YOU for this part of the code which is very useful to monitoring SVXReflector.
Do you have a suggestion about svxreflector log rotate ???

73 Waldek SP2ONG

**Comment by SkyAndy** [comment]
Hello, Waldek
thank you for the flowers. It is possible to keep a record in a cookie 48h hours when the log file is empty. I'm thinking about it.
73 Andy DO7EN

**Comment by sp2ong** [comment]
Hi Andy,

Is it possible setup how many last rows will be displayed from log file in window "logfile"?
It will be nice to have this because for me maybe last 20 rows from log file will be OK

73 Waldek

**Comment by sp2ong** [comment]
Ok , I have found this definition in config file :-)

**Comment by SkyAndy** [comment]
Hey Waldek ! 
please test it and give me an feedback for closing Issues.
