### ISSUE TITLE
log rotate svxreflector

### ISSUE THREAD

**Issue by sp2ong** [SkyAndy/svxrdb#5]
Andy, how the "RECOVER" option works. I have set YES in the configuration file but this morning when the system run log rotate, the svxreflector log was empty and when I have open the status page was empty without information

73 Waldek

**Comment by SkyAndy** [comment]
Moin moin,
Have you found in your folder a file that has the name
recover_data_svxlinkreflector.log and define ("RECOVER", "YES"); ?

The name is thus composed.
recover_data_xxxxx
xxxx = $ LOGFILES = array ('svxlinkreflector.log', '', '');
recover_data_svxlinkreflector.log file name.
The file stores all the data that the array can have.
Do you find data in this file when LOGFILES is YES?

**Comment by sp2ong** [comment]
Hi,

I have in config file $ LOGFILES = array ('/var/log/svxkreflector', '', '');
and I did not find recover_data_svxreflector in /var/log

**Comment by SkyAndy** [comment]
inside the directory from you ...../svxrdb/

**Comment by sp2ong** [comment]
Ok, I have solved problem. I have make symbol link to svxreflector log from /var/log to name svxreflector.log in /var/www/html/svxrdb/ and put in config file instead "/var/log/svxreflector" "svxreflectror.log" and now I have see file recover_data_svxreflectro.log in /var/www/html/svxrdb/
