### ISSUE TITLE
Log rotate and not recovery full information

### ISSUE THREAD

**Issue by sp2ong** [SkyAndy/svxrdb#6]
Hi Andy,

I have still observer problem with log rotate and lose information about login/logout time after log rotate
and get data from recovery file. It maybe I must change the start time of log rotate or other. I will try to find where is problem

**Comment by sp2ong** [comment]
It maybe it is problem when in one time meet 2 processes one with logrotate and create recovery data file

**Comment by SkyAndy** [comment]
create a cronjob with "php create_html.php> /tmp/analyse_svxrdb.txt". Then check if the file recover_data_xxxxx exists in ..www... /svxrdb/ directory and what is in the /tmp/analyse_svxrdb.txt. in addition you can still insert in each php file the following line. "Error_reporting (1);"

**Comment by sp2ong** [comment]
Ok I will try find solution this problem

**Comment by SkyAndy** [comment]
only data from clients will saved as bkp....not any line from logfile

**Comment by sp2ong** [comment]
Hi Andy,

I have updated to latest version svxrb and switch on RECOVERY and it looks like all works OK after system log rotate.

73 Waldek
