### ISSUE TITLE
Content of tooltip

### ISSUE THREAD

**Issue by sp2ong** [SkyAndy/svxrdb#7]
Hi Andy,

I have seen that on your page content of tooltip is like "City name / Frequency" on my site I have
info "New client time" 
How to put similar information in a tooltip like on your status page ???

Waldek

**Comment by SkyAndy** [comment]
Hello Waldek,
this is not a "issues". Please ask such questions that no errors or problems are not as "issues" in github. Issues are errors in the code, or other problems affecting the program itself. thx

You can specify your data in the file create_html.php / * EXTRA INFO EXAMPLE DO0SE Server * / there is an example.

Andy
